'use strict'

import React, {Component, useState} from 'react'
import Modal from 'react-native-modal';
import {
    View,
    Text,
    StyleSheet,
    Image,
    Dimensions
   } from 'react-native'


   /**
    * Components
    *  -Question View - to house the question
    *  -Answer View - to hold the answers
    *  -Question format:
    *      - Present a text question with picture-base options for answers
    *      - Present an unknow Picture and word options
    * 
    *  Implementation 
    *   - a boolean will determine the type of question to present [picture or word]
    *   - an array will hold the possible answers to the questions 
    *   - users selection will be compared 
    * 
    * Flow: click-on-quiz-level -> get-quiz-data -> init-UI-with-quiz-data -> iterate-and-create-quiz-UI
    * 
    * inputs: 
    *   difficulty (context)
    *   Quiz-Data: will be randamly generated by base on level of difficulty 
    *       
    * 
    */

    const QuestionView = ()=>{
        const titleText = useState("Bird's Nest");

        return <View style={styles.quest}>
                    <Text> {titleText}</Text> 
               </View> 
    }

    const AnswerView = () => {
        const titleText = useState("Bird's Nest");

        return <View style={styles.ans}>
                    <Text>{titleText}</Text>
              </View>
    }

    export default class McqCard extends React.Component{

        constructor(props){
            super()
            this.state = {
                isVisible: true
            }

            this.toggleModal = this.toggleModal.bind(this)
        }

        toggleModal(){
            this.setState((state)=>({
                 isVisible:!state.isVisible
            }))
        }
        render(){

            return <>
                <Modal
                    style={styles.modal}
                    isVisible={this.state.isVisible}
                    onBackdropPress={()=>this.toggleModal()}
                >

                    <QuestionView/>
                    <AnswerView/>

                </Modal>
                    
            </>
        }
    }


    const styles = StyleSheet.create({
        modal:{
            backgroundColor: 'white',
            maxHeight:Dimensions.get('window').height/2,
            justifyContent: 'center',
            textAlign: 'center'
        },

        quest:{
            backgroundColor: 'white',
            minHeight:'40%'
        },
        ans:{
            backgroundColor: 'skyblue',
            minHeight:'60%'
        }
    })