'use strict'

import React, {useState} from 'react';
import {
    View,
    Text,
    StyleSheet,
    Image,
    TouchableOpacity,
    Dimensions
   } from 'react-native'
   import {Card} from 'react-native-shadow-cards'
   
   import {images} from '../../../utility/Service/ImgProvider'

   /**
    * Components
    *  -Question View - to house the question
    *  -Answer View - to hold the answers
    *  -Question format:
    *      - Present a text question with picture-base options for answers
    *      - Present an unknow Picture and word options
    * 
    *  Implementation 
    *   - a boolean will determine the type of question to present [picture or word]
    *   - an array will hold the possible answers to the questions 
    *   - users selection will be compared 
    * 
    * Flow: click-on-quiz-level -> get-quiz-data -> init-UI-with-quiz-data -> iterate-and-create-quiz-UI
    * 
    * inputs: 
    *   difficulty (context)
    *   Quiz-Data: will be randamly generated by base on level of difficulty 
    *       
    * 
    *  What do you see?
    *  What do you hear?
    *  What do you read? 
    *  Tap the matching pair
    * 
    *    
    */
    const TextQuestionView = (props)=>{
        const titleText = props.content;
        let mstyle = JSON.parse(JSON.stringify(styles.quest))
        mstyle.height='20%'

        return <Card style={mstyle}>
                    <Text style={styles.questText}> {titleText}</Text> 
            </Card> 
    }

    /**
     * input: props.content[question, imageurl]
     */
    const QuestionViewWithImage = (props)=>{
        const titleText = props.content.text;
        imageurl = props.content.imageurl
        return <Card style={styles.quest}>
                    <View style={styles.quest_img}>
                        <Image  style={styles.image}
                                source={imageurl}
                                resizeMode='contain'/>
                    </View>
                    <Text style={styles.questText}> {titleText}</Text> 
               </Card> 
    }

    const TextAnswerView = (props) => {

        let hightlightAns = (showResult, results, ansOption) => {
            
            console.log("hightlightAns: "+showResult)
            console.log("hightlightAns results: "+results)
            if(showResult == false || results == null){
                return styles.ans
            }
            console.log("Tyep style: "+ (Object.values(results)))

            let mstyle = JSON.parse(JSON.stringify(styles.ans))
            
            if(results.isCorrect == true && results.correctAns == ansOption){
                mstyle.borderWidth = 2
                mstyle.borderColor = '#98fb98'
                return mstyle
            }else if (results.isCorrect == true) return mstyle;

            if(results.isCorrect == false && results.selectedAns == ansOption){   
                mstyle.borderWidth = 1
                mstyle.borderColor = 'red'
            }else if (results.correctAns == ansOption){
                mstyle.borderWidth = 2
                mstyle.borderColor = '#98fb98'
            }

            return mstyle
        }//hightlightAns Ends 

        options = props.content
                   
       
        return <View style={[styles.ansView]}> 
                    {options.map(element => ( 
                            <Card key={element} style={hightlightAns(props.showResult, props.result, element)}>
                                 <TouchableOpacity 
                                     style={styles.touchableView}
                                     onPress={ ()=>{
                                        props.onAswer(VIEW_TYPES.TEXT_ANS_VIEW, element)}
                                     }
                                     >
                                     
                                    <Text> {element} </Text>
                                 </TouchableOpacity>
                                
                            </Card> ))} 
                </View>
    }//TextAnswerView Ends

    const AnswerCell = (props) => {
        const [borderWidth, setBorderWith] = useState(0)
        let mStyle = JSON.parse(JSON.stringify(props.style))
        mStyle.borderWidth = borderWidth
        mStyle.borderColor = props.borderColor

        const hightlightCell=()=>{
            
            new Promise( (resolve) => {if(borderWidth==0){
                                setBorderWith(2)
                            }else{
                                setBorderWith(0)
                            }
                            resolve()
                        }).then(()=>{
                            props.parentCallBack(props.cellKey, mStyle.borderColor, props.column)
                        })
        }   
       
     
        return <Card style={mStyle}>
                <TouchableOpacity style={styles.touchableView}
                    onPress={ ()=>{
                        //props.onSelect(element.img, "left")
                        hightlightCell()
                    }}>
                    {props.childView}
                </TouchableOpacity>
            </Card>
    }
    
    const AnswerViewMatchWordAndImage = (props) => {
        
        let localStyle = StyleSheet.create({
            element:{
                flex: 1,
                height: '100%',
                width: '100%',
                marginHorizontal: '1%',
                alignSelf:'center'
             },
            container:{
                flex: 1,
                height: '100%',
                width: '100%',
                flexDirection:'row',
                marginBottom: '1%',
                justifyContent:'space-evenly'
            }
             
        })

        const [selectedWord, setSelectWord] = useState([])
        //const [activeElement, setActiveElement] = useState("")
        const [mode, setMode] = useState("select")
        const [touchCount, setTouchCount] = useState(0)
        const [nextColor, setNextColor] = useState(0)

        const colors = ["yellow", "green", "blue", "pink"]

        let onSelect = (key, color, leftRight) =>{
            setTouchCount(touchCount+1)
            console.log("Onselect triggered by "+ key)
            let tempMatched = JSON.parse(JSON.stringify(selectedWord))
            tempMatched.push(key+"_"+color)
            setSelectWord([tempMatched] )
            console.log("activeColor values "+tempMatched)
            
            //console.log("mode mode mode  mode "+ mode)
        }

        React.useEffect( () => {
            console.log("Touch count "+ touchCount)
            if(touchCount%2 == 0 && touchCount != 0){
                setNextColor(nextColor+1)
            } 
        }, [touchCount] )

        let highlight = (itemData)=>{
            let selected = JSON.parse(JSON.stringify(selectedWord)).toString().split(",")
            if(selected.length > 0){
                for ( let i in selected ){
                    //console.log(selected[i] + " Looking "+ i)
                    let parts = selected[i].split("_")
                    if(parts[0] == itemData){
                        //console.log("Found "+ itemData + " with color ")
                        return parts[1]
                    }
                }

                return colors[nextColor] 
            } 
          
            return colors[nextColor] 
        }
        return <View style={styles.ansView}> 
                    {props.content.map( (element, index)=> {
                        const leftElement = (<Image  style={styles.image}
                                                source={images[element.img]}
                                                resizeMode='contain'/>)
                        const rightElement = (<Text>{element.text}</Text>)
                        
                        return ( 
                                <View key={index} style={localStyle.container}>
                                    
                        
                                    <AnswerCell
                                        borderColor={highlight("img:"+element.img)}
                                        cellKey={("img:"+element.img)}
                                        style={localStyle.element}
                                        childView={leftElement}
                                        column="left"
                                        parentCallBack={onSelect}
                                    />
                                    <AnswerCell
                                        borderColor={highlight("text:"+element.text)}
                                        cellKey={("text:"+element.text)}
                                        style={localStyle.element}
                                        childView={rightElement}
                                        column="right"
                                        parentCallBack={onSelect}
                                    />

                                </View> 
                            )}
                        )
                    } 
                </View>
    }

    const AnswerViewWithImage = (props) => {
        
        let localStyle = StyleSheet.create({
            imgContainer:{
                height: '40%',
                width: '48%',
                marginHorizontal: '1%'
             },
            container:{
                height: '100%',
                width: '100%',
                flex: 1,
                justifyContent:'space-around',
                flexDirection:'column',
                flexWrap: 'wrap',
                backgroundColor: 'white',
            }
             
        })
        return <View style={localStyle.container}> 
                    {props.content.map(element => ( 
                                <Card style={localStyle.imgContainer}>
                                    <TouchableOpacity style={styles.touchableView}>
                                        <Image  style={styles.image}
                                                source={require('../../../../resource/img/rooster.png')}
                                                resizeMode='contain'/>
                                    </TouchableOpacity>
                                    
                                </Card>
                            )
                        )
                    } 
                </View>
    }

    export const VIEW_TYPES = {
        QUEST_VIEW_WITH_IMAGE: 'QUEST_VIEW_WITH_IMAGE',
        TEXT_QUEST_VIEW: 'TEXT_QUEST_VIEW',
        ANS_VIEW_WITH_IMAGE:'ANS_VIEW_WITH_IMAGE',
        ANS_VIEW_MATCH_TEXT_IMAGE: 'ANS_VIEW_MATCH_TEXT_IMAGE',
        TEXT_ANS_VIEW: 'TEXT_ANS_VIEW'
    }

    const resolveQuestionView = (viewType) => {
        if(viewType == VIEW_TYPES.QUEST_VIEW_WITH_IMAGE){
            return QuestionViewWithImage
        }else {
            return TextQuestionView
        }
    }

    const resolveAnswerView = (viewType) => {
        if(viewType == VIEW_TYPES.ANS_VIEW_WITH_IMAGE){
            return AnswerViewWithImage
        }else if(viewType == VIEW_TYPES.ANS_VIEW_MATCH_TEXT_IMAGE){
            return AnswerViewMatchWordAndImage
        }else {
            return TextAnswerView
        }
    }
    export default class CardComponent extends React.Component{

        constructor(props){
            super(props)
            this.state = {
                isVisible: true,
                content: {}
            }

        }
        componentDidMount(){
            console.log("MCQ component mounted")
        }
        render(){
            const QuestionView = resolveQuestionView(this.props.questViewType)
            const AnswerView = resolveAnswerView(this.props.ansViewType)
            
            return <>
                    <QuestionView
                        content={this.props.question}
                    />
                    
                    <AnswerView
                        content={this.props.answer}
                        onAswer={this.props.onAswer}
                        showResult={this.props.showResult}
                        result={this.props.result}
                      />
                    </>               
        }
    }


   const styles = StyleSheet.create({
        quest:{
            backgroundColor: 'white',
            height: '40%',
            width: '98%',
            margin: '1%',
            alignSelf: "center",
            alignItems:'center',
            justifyContent: "center"            
        },
        quest_img:{
            height: '60%',
            width: '40%',
            backgroundColor:'white'
        },
        questText:{
            fontSize:20
        },
        image: {
            alignSelf:'center',
            width: '100%',
            height: '100%',
        },
        ans:{
            backgroundColor: 'white',
            flex: 1,
            width: '90%',
            marginVertical: 20,
            justifyContent:'center',
            alignSelf:'center',
            alignItems:'center'
        },
        ansView:{
            backgroundColor: 'white',
            flex: 1,
            width: '100%'
        },
        touchableView:{
            height: '100%',
            width: '100%',
            justifyContent:'center',
            alignItems:'center'
        }
    })