//'use strict'

import React, {useState} from 'react'
import Modal from 'react-native-modal';
import {
    View,
    Text,
    StyleSheet,
    Image,
    SafeAreaView,
    Dimensions
   } from 'react-native'
   import GridAdapter from '../../../utility/Layout/Grid/GridAdapter'

   const imageUrl = "https://via.placeholder.com/150";

   /**
    * Components
    *  -Question View - to house the question
    *  -Answer View - to hold the answers
    *  -Question format:
    *      - Present a text question with picture-base options for answers
    *      - Present an unknow Picture and word options
    * 
    *  Implementation 
    *   - a boolean will determine the type of question to present [picture or word]
    *   - an array will hold the possible answers to the questions 
    *   - users selection will be compared 
    * 
    * Flow: click-on-quiz-level -> get-quiz-data -> init-UI-with-quiz-data -> iterate-and-create-quiz-UI
    * 
    * inputs: 
    *   difficulty (context)
    *   Quiz-Data: will be randamly generated by base on level of difficulty 
    *       
    * 
    */

    const QuestionView = ()=>{
        const titleText = "What is the question?";

        return <View style={styles.quest}>

                    <Image 
                        style={styles.image }
                        source={ {uri:imageUrl} }
                        resizeMode = 'cover'
                    />

                    <Text> {titleText}</Text> 
               </View> 
    }

    const AnswerView = () => {
        const [dataSource, setDataSource] = useState(["1","2","3","4"]);
        

        itemUiSet = ()=>{
            uiElements = []; 
            dataSource.forEach(element => {
            uiElements.push( { text:element, 
                    displayObj:(<Text style={{alignSelf:'center'}}>{element}</Text>),
                    showTitle: false
                 });
            });

            return uiElements
        }

        dataUi = itemUiSet()

        return <View style={[styles.ans]}> 
                    <GridAdapter
                        data={dataUi}
                        canSelectItem = {false}
                        isScrollable={false}
                        onCellPressed = {(answer)=>{
                        console.log("Category cell pressed: ["+answer+"]");
                        }}
                    />
                </View>
    }

    export default class McqCard extends React.Component{

        constructor(props){
            super(props)
            this.state = {
                isVisible: true
            }

        }
        componentDidMount(){
            console.log("MCQ component mounted")
        }
        render(){

            return <>
                      <QuestionView/>
                      <AnswerView/>
                    </>               
        }
    }


    const styles = StyleSheet.create({
        
        mainView:{
            backgroundColor:"blue"
        },
        quest:{
            backgroundColor: 'white',
            flex: 1,
            alignItems: "center",
            justifyContent: "center"
            
        },
        ans:{
            backgroundColor: 'skyblue',
            flex: 1,
            alignSelf: 'center'
        }
    })