//'use strict'

import React, {useState} from 'react'
import Modal from 'react-native-modal';
import {
    View,
    Text,
    StyleSheet,
    Image,
    SafeAreaView,
    Dimensions
   } from 'react-native'
   import {Card} from 'react-native-shadow-cards'

   import GridAdapter from '../../../utility/Layout/Grid/GridAdapter'

   const imageUrl = "https://via.placeholder.com/150";

   /**
    * Components
    *  -Question View - to house the question
    *  -Answer View - to hold the answers
    *  -Question format:
    *      - Present a text question with picture-base options for answers
    *      - Present an unknow Picture and word options
    * 
    *  Implementation 
    *   - a boolean will determine the type of question to present [picture or word]
    *   - an array will hold the possible answers to the questions 
    *   - users selection will be compared 
    * 
    * Flow: click-on-quiz-level -> get-quiz-data -> init-UI-with-quiz-data -> iterate-and-create-quiz-UI
    * 
    * inputs: 
    *   difficulty (context)
    *   Quiz-Data: will be randamly generated by base on level of difficulty 
    *       
    * 
    *  What do you see?
    *  What do you hear?
    *  What do you read? 
    *  Tap the matching pair
    */
    const QuestionView = ()=>{
        const titleText = "What is the question?";

        return <View style={styles.quest}>
                    <View style={styles.quest_img}>
                        <Image  style={styles.image}
                                source={require('../../../../resource/img/rooster.png')}
                                resizeMode='cover'/>
                    </View>
                    <Text style={styles.questText}> {titleText}</Text> 
               </View> 
    }

    const AnswerView = (props) => {
        
        return <View style={[styles.ansView]}> 
                    {props.dataSource.map(element => ( 
                            <Card style={[styles.ans]}> 
                                <Text key={element}> {element} </Text>
                            </Card> ))} 
                </View>
    }

    export default class McqCard extends React.Component{

        constructor(props){
            super(props)
            this.state = {
                isVisible: true
            }

        }
        componentDidMount(){
            console.log("MCQ component mounted")
        }
        render(){

            return <>
                      <QuestionView/>
                      <AnswerView
                        dataSource={["lion","bird","zebra","basket"]}
                      />
                    </>               
        }
    }


    const styles = StyleSheet.create({
        
        quest:{
            backgroundColor: 'white',
            height: '40%',
            alignItems: "center",
            justifyContent: "center"            
        },
        quest_img:{
            height: '60%',
            width: '40%',
            backgroundColor:'green'
        },
        questText:{
            fontSize:20
        },
        image: {
            flex: 1,
            alignSelf:'stretch',
            width: undefined,
            height: undefined,
        },
        ans:{
            backgroundColor: 'white',
            flex: 1,
            width: '90%',
            marginVertical: 20,
            justifyContent:'center',
            alignSelf:'center',
            alignItems:'center'
        },
        ansView:{
            backgroundColor: 'white',
            flex: 1,
            width: '100%'
        }
    })